services:
  vertx-demo:
    image: marekdudek/vertx-demo:1.0.4
    container_name: vertx-demo
    ports:
      - "80:8080"
    environment:
      JAVA_TOOL_OPTIONS: >
        -Dlogback.configurationFile=/logs/logback.xml
    volumes:
      - ./logs/:/logs/:rw
