services:
  config-server-nginx:
    container_name: config-server-nginx
    image: nginx
    ports:
    - "8887:80"
    volumes:
    - read_only: false
      source: ./configs/
      target: /usr/share/nginx/html
      type: bind
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=vertx_demo_database
      - POSTGRES_USER=vertx_demo_user
      - POSTGRES_PASSWORD=vertx_demo_password
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U vertx_demo_user -d vertx_demo_database
      interval: 3s
      timeout: 1s
      retries: 10
  vertx-demo:
    command: |
      -conf='{
        "config-server": {
          "host": "host.docker.internal",
          "path": "/conf.json",
          "port": 8887,
          "scan-period": "PT5S",
          "version": "DEV inline"
        },
        "http.port": 8081,
        "telnet.port": 5001,
        "postgres" : {
          "host" : "host.docker.internal",
          "port" : 5432,
          "database" : "vertx_demo_database",
          "user" : "vertx_demo_user",
          "password" : "vertx_demo_password"
        }
      }
      '
    container_name: vertx-demo
    depends_on:
    - config-server-nginx
    - postgres
    environment:
      JAVA_TOOL_OPTIONS: |
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
        -Dlogback.configurationFile=/logs/logback.xml
        -Djava.net.preferIPv4Stack=true
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.port=1099
        -Dcom.sun.management.jmxremote.rmi.port=1099
        -Djava.rmi.server.hostname=0.0.0.0
      VERSION: 1.0.12-SNAPSHOT
    image: marekdudek/vertx-demo:1.0.12-SNAPSHOT
    ports:
    - "8081:8081"
    - "5005:5005"
    - "5001:5001"
    - "1099:1099"
    volumes:
    - read_only: false
      source: ./logs/
      target: /logs/
      type: bind
    - read_only: false
      source: ./log-data/
      target: /log-data/
      type: bind
