services:
  config-server-nginx:
    container_name: "config-server-nginx"
    image: nginx
    ports:
    - "8887:80"
    volumes:
    - read_only: false
      source: ./configs/
      target: /usr/share/nginx/html
      type: bind
  postgres:
    container_name: postgres
    environment:
      POSTGRES_DB: vertx_demo_dev_database
      POSTGRES_PASSWORD: vertx_demo_dev_password
      POSTGRES_USER: vertx_demo_dev_user
    healthcheck:
      interval: 3s
      retries: 10
      test: "pg_isready -U vertx_demo_dev_user -d vertx_demo_dev_database"
      timeout: 1s
    image: postgres
    ports:
    - "5432:5432"
    restart: "unless-stopped"
  qpid:
    container_name: qpid
    environment:
      JAVA_GC: "-XX:+UseG1GC"
      JAVA_MEM: "-Xmx256m -XX:MaxDirectMemorySize=128m"
      JAVA_OPTS: ''
      QPID_ADMIN_PASSWORD: dev_secret
      QPID_ADMIN_USER: dev_admin
    healthcheck:
      interval: 5s
      retries: 3
      test: "curl -u dev_admin:dev_secret --basic -o /dev/null -f -w %{http_code} http://dev_admin:dev_secret@host.docker.internal:15672/api/latest/broker"
      timeout: 3s
    image: "apache/qpid-broker-j"
    ports:
    - "5672:5672"
    - "15672:8080"
    volumes:
    - read_only: false
      source: ./qpid/default.json
      target: "/qpid-broker-j/work-init/default.json"
      type: bind
  vertx-demo:
    command: |
      -conf='{
        "amqp": {
          "client": {
            "delay": 1000,
            "queue": "client-queue"
          },
          "host": "qpid",
          "password": "dev_secret",
          "port": 5672,
          "reconnect-attempts": 2147483647,
          "reconnect-interval": 100,
          "server": {
            "delay": 1000,
            "queue": "server-queue"
          },
          "username": "dev_admin"
        },
        "config-server": {
          "host": "host.docker.internal",
          "path": "/conf.json",
          "port": 8887,
          "scan-period": "PT5S",
          "version": "DEV inline"
        },
        "http.port": 8081,
        "postgres": {
          "database": "vertx_demo_dev_database",
          "host": "host.docker.internal",
          "password": "vertx_demo_dev_password",
          "port": 5432,
          "ssl-mode": "disable",
          "trust-all": false,
          "user": "vertx_demo_dev_user"
        },
        "telnet.port": 5001
      }
      '
    container_name: "vertx-demo"
    depends_on:
    - "config-server-nginx"
    - postgres
    - qpid
    environment:
      JAVA_TOOL_OPTIONS: |
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
        -Dlogback.configurationFile=/logs/logback.xml
        -Djava.net.preferIPv4Stack=true
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.port=1099
        -Dcom.sun.management.jmxremote.rmi.port=1099
        -Djava.rmi.server.hostname=0.0.0.0
      VERSION: "1.0.14-SNAPSHOT"
    image: "marekdudek/vertx-demo:1.0.14-SNAPSHOT"
    ports:
    - "8081:8081"
    - "5005:5005"
    - "5001:5001"
    - "1099:1099"
    volumes:
    - read_only: false
      source: ./logs/
      target: /logs/
      type: bind
    - read_only: false
      source: "./log-data/"
      target: "/log-data/"
      type: bind
