services:
  vertx-demo:
    image: marekdudek/vertx-demo:${tag}
    container_name: vertx-demo
    ports:
      - "80:8080"
      - "5005:5005"
      - "5000:5000"
    environment:
      JAVA_TOOL_OPTIONS: >
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
        -Dlogback.configurationFile=/logs/logback.xml
      TAG: ${tag}
    command: >-
      -conf='{
        "name": "value"
      }'
    volumes:
      - ./logs/:/logs/:rw
      - ./log-data/:/log-data/:rw
