services:
  vertx-demo:
    image: marekdudek/vertx-demo:${tag}
    container_name: vertx-demo
    ports:
      - "80:8080"
      - "5005:5005"
      - "5000:5000"
      - "1099:1099"
    environment:
      JAVA_TOOL_OPTIONS: >
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
        -Dlogback.configurationFile=/logs/logback.xml
        -Djava.net.preferIPv4Stack=true
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.port=1099
        -Dcom.sun.management.jmxremote.rmi.port=1099
        -Djava.rmi.server.hostname=ec2-13-60-243-123.eu-north-1.compute.amazonaws.com
      VERSION: ${tag}
    command: >-
      -conf='{
        "config-server": {
          "host": "51.21.163.63",
          "path": "/conf.json",
          "port": 8887,
          "scan-period": "PT30S",
          "version": "PROD inline"
        }
      }'
    volumes:
      - ./logs/:/logs/:rw
      - ./log-data/:/log-data/:rw

  config-server-nginx:
    image: nginx
    container_name: config-server-nginx
    ports:
      - "8887:80"
    volumes:
      - ./configs:/usr/share/nginx/html:rw
